📁 backend/app/routes/nuvexa.py
📁 frontend/pages/
  ├─ nuvexa-admin.tsx
  ├─ nuvexa-ai.tsx
  ├─ nuvexa-cpd.tsx
  ├─ nuvexa-export.tsx
  ├─ nuvexa-language.tsx
  ├─ nuvexa-personas.tsx
  ├─ nuvexa-records.tsx
  ├─ nuvexa-robotics.tsx
  ├─ nuvexa-training.tsx
  ├─ nuvexa-triage.tsx
  ├─ nuvexa-telemetry.tsx
  ├─ nuvexa.tsx
  ├─ nuvexa-video.tsx
  └─ NuvexaOverlayGrid.tsx