name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t frontend ./geniqx/frontend
      - run: docker build -t backend ./geniqx/backend
