# backend/app/routes/legal_documents_api.py

from flask import Blueprint, request, jsonify
import uuid
from datetime import datetime

legal_bp = Blueprint("legal_documents", __name__)

@legal_bp.route("/legal/generate", methods=["POST"])
def generate_legal_doc():
    data = request.get_json()
    category = data.get("category", "contract")
    jurisdiction = data.get("jurisdiction", "UK")
    intent = data.get("intent", "prenuptial agreement")

    doc_id = f"LAW-{uuid.uuid4().hex[:6].upper()}"
    filename = f"{category}_{intent.replace(' ', '_')}_{jurisdiction}.pdf".lower()

    disclaimer = (
        "This document is generated by GENIQX Legal AI and does not constitute legal advice. "
        "Please consult a qualified legal professional before acting on its contents."
    )

    instructions = f"This is a {intent} prepared for {jurisdiction} law. Read carefully before signing. Attach identification and supporting documents where applicable."

    legal_bundle = {
        "doc_id": doc_id,
        "filename": filename,
        "category": category,
        "intent": intent,
        "jurisdiction": jurisdiction,
        "disclaimer": disclaimer,
        "instructions": instructions,
        "fields_required": ["full_name", "address", "date", "witness_signature"],
        "timestamp": datetime.utcnow().isoformat()
    }

    return jsonify(legal_bundle)
