services:
  - type: web
    name: geni-commandcore-backend
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: "python backend/app.py"

  - type: web
    name: geni-commandcore-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "frontend/out"
