require Pod::Executable.execute_command('node', ['-e',
  "process.stdout.write(require('react-native/scripts/react_native_pods').js_from_package_json_path())",
]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'GeniQX' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  target 'GeniQXTests' do
    inherit! :complete
  end
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
